// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/jewzaam/pod-operator/pkg/apis/pod/v1alpha1.PodRequest":       schema_pkg_apis_pod_v1alpha1_PodRequest(ref),
		"github.com/jewzaam/pod-operator/pkg/apis/pod/v1alpha1.PodRequestSpec":   schema_pkg_apis_pod_v1alpha1_PodRequestSpec(ref),
		"github.com/jewzaam/pod-operator/pkg/apis/pod/v1alpha1.PodRequestStatus": schema_pkg_apis_pod_v1alpha1_PodRequestStatus(ref),
	}
}

func schema_pkg_apis_pod_v1alpha1_PodRequest(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PodRequest is the Schema for the podrequests API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/jewzaam/pod-operator/pkg/apis/pod/v1alpha1.PodRequestSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/jewzaam/pod-operator/pkg/apis/pod/v1alpha1.PodRequestStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/jewzaam/pod-operator/pkg/apis/pod/v1alpha1.PodRequestSpec", "github.com/jewzaam/pod-operator/pkg/apis/pod/v1alpha1.PodRequestStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_pod_v1alpha1_PodRequestSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PodRequestSpec defines the desired state of PodRequest",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_pod_v1alpha1_PodRequestStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PodRequestStatus defines the observed state of PodRequest",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
